### ISSUE TITLE
Digital - Button

### ISSUE THREAD

**Issue by ferauche** [santos-hacker-clube/aprenda_micropython#10]
Fazer o código semelhante a https://github.com/arduino/arduino-examples/tree/main/examples/02.Digital/Button

**Comment by hmartiins** [comment]
Quando puder me deixe responsável por essa tarefa por favor.

**Comment by hmartiins** [comment]
Agora que me atribuíram função de colaborador não precisa mais me atribuir a tarefa, já consegui fazer isso.
