### ISSUE TITLE
Control -> WhileStatementConditional

### ISSUE THREAD

**Issue by ferauche** [santos-hacker-clube/aprenda_micropython#25]
Realizar o código conforme https://github.com/arduino/arduino-examples/tree/main/examples/05.Control/IfStatementConditional

Pasta dos arquivos: Control/IfStatementConditional

**Comment by gabrielzy18** [comment]
https://github.com/arduino/arduino-examples/tree/main/examples/05.Control/WhileStatementConditional

**Comment by ferauche** [comment]
Feito no pull request #32 realizado o WhileStatement gerado a tarefa #33 para correção da pasta
