### ISSUE TITLE
Wifi -> WifiScan

### ISSUE THREAD

**Issue by ferauche** [santos-hacker-clube/aprenda_micropython#50]
https://github.com/espressif/arduino-esp32/tree/master/libraries/WiFi/examples/WiFiScan

**Comment by joaopmaximo** [comment]
Mantive todo o código em um só arquivo. Notei que no seu exemplo WifiConnection você utiliza o Garbage Collector e desativa os logs no prompt, fiquei com dúvida se seria ideal fazer o mesmo nesse exemplo.

**Comment by ferauche** [comment]
Feito no pullrequest #52
